=== Awanish-26/C-for-Collage/Web-Dev/students.dtd
<!ELEMENT students (student+)>
<!ELEMENT student (name, age, email, enrollmentDate)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT enrollmentDate (#PCDATA)>

=== Awanish-26/C-for-Collage/Web-Dev/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="students.css"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
    <student>
        <name>John Doe</name>
        <age>20</age>
        <email>john.doe@example.com</email>
        <enrollmentDate>2023-09-01</enrollmentDate>
    </student>
    <student>
        <name>Jane Smith</name>
        <age>22</age>
        <email>jane.smith@example.com</email>
        <enrollmentDate>2022-09-01</enrollmentDate>
    </student>
    <student>
        <name>Emily Johnson</name>
        <age>21</age>
        <email>emily.johnson@example.com</email>
        <enrollmentDate>2021-09-01</enrollmentDate>
    </student>
</students>
